### ISSUE TITLE
pdf download fails in cost analysis page

### ISSUE THREAD

**Issue by whdalsrnt** [cloudforet-io/console#648]
Hello one of our customer is experiencing issue while downloading pdf in cost analysis page.

Cost Explorer > Cost Analysis 

When click 'PDF' button. No response on pdf rendering page as below

![Image](https://user-images.githubusercontent.com/53893313/210735582-22636ddb-7341-4305-b297-161434e7f944.png)

In developer tool error message appears when I click 'pdf' button

![Image](https://user-images.githubusercontent.com/53893313/210735878-fb134878-2292-4cd8-88bd-1a07d9394b50.png)

**Comment by sulmoJ** [comment]
https://github.com/cloudforet-io/console/pull/487
